//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOKING
    {
        public int RENT_ID { get; set; }
        public Nullable<int> CAR_ID { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> Orderdate { get; set; }
        public Nullable<System.DateTime> FROM_DATE { get; set; }
        public Nullable<System.DateTime> RETURN_DATE { get; set; }
        public Nullable<System.DateTime> ACTUAL_RETURN_DATE { get; set; }
        public Nullable<double> AMOUNT { get; set; }
        public Nullable<double> LATE_FEE { get; set; }
        public Nullable<double> DISCOUNT { get; set; }
        public Nullable<double> TOTAL_AMOUNT { get; set; }
    
        public virtual CAR CAR { get; set; }
        public virtual SIGNUP SIGNUP { get; set; }
    }
}
