//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAR
    {
        public CAR()
        {
            this.BOOKINGs = new HashSet<BOOKING>();
            this.CARTs = new HashSet<CART>();
        }
    
        public int CAR_ID { get; set; }
        public string MODEL { get; set; }
        public int MODEL_YEAR { get; set; }
        public string COLOR { get; set; }
        public int NUMBER_OF_PERSONS { get; set; }
        public int DAILY_RENT { get; set; }
        public string IMAGES { get; set; }
    
        public virtual ICollection<BOOKING> BOOKINGs { get; set; }
        public virtual ICollection<CART> CARTs { get; set; }
    }
}
