//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CAR_RENTEntities : DbContext
    {
        public CAR_RENTEntities()
            : base("name=CAR_RENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BOOKING> BOOKINGs { get; set; }
        public DbSet<CAR> CARs { get; set; }
        public DbSet<CART> CARTs { get; set; }
        public DbSet<CONTACTU> CONTACTUS { get; set; }
        public DbSet<SIGNIN> SIGNINs { get; set; }
        public DbSet<SIGNUP> SIGNUPs { get; set; }
    }
}
