//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIGNUP
    {
        public SIGNUP()
        {
            this.BOOKINGs = new HashSet<BOOKING>();
            this.CARTs = new HashSet<CART>();
            this.CONTACTUS = new HashSet<CONTACTU>();
            this.SIGNINs = new HashSet<SIGNIN>();
        }
    
        public int CUSTOMER_ID { get; set; }
        public string NAME { get; set; }
        public string EMAIL { get; set; }
        public Nullable<System.DateTime> DATE_OF_BIRTH { get; set; }
        public string CONTACT_NUMBER { get; set; }
        public string CITY { get; set; }
        public string STATE { get; set; }
        public string ZIPCODE { get; set; }
        public string PASSWORD { get; set; }
    
        public virtual ICollection<BOOKING> BOOKINGs { get; set; }
        public virtual ICollection<CART> CARTs { get; set; }
        public virtual ICollection<CONTACTU> CONTACTUS { get; set; }
        public virtual ICollection<SIGNIN> SIGNINs { get; set; }
    }
}
