// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CarUnitTest
{
    public partial class Signup
    {
        public Signup()
        {
            Bookings = new HashSet<Booking>();
            Carts = new HashSet<Cart>();
            Contactus = new HashSet<Contactu>();
            Signins = new HashSet<Signin>();
        }

        public int CustomerId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string ContactNumber { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zipcode { get; set; }
        public string Password { get; set; }

        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual ICollection<Contactu> Contactus { get; set; }
        public virtual ICollection<Signin> Signins { get; set; }
    }
}