// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentNRunLib
{
    public partial class Contactus
    {
        public int ContactusId { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Subjects { get; set; }
        public string Message { get; set; }

        public virtual Signup EmailNavigation { get; set; }
    }
}