// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace RentNRunLib
{
    public partial class Signup
    {
        public Signup()
        {

            Bookings = new HashSet<Booking>();
            Contactus = new HashSet<Contactus>();
            Feedbacks = new HashSet<Feedback>();
            Signins = new HashSet<Signin>();
        }

        public int CustomerId { get; set; }


        [Required(ErrorMessage = "Please Enter The Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please Enter The Email")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please Enter The Date Of Birth")]
        
        public DateTime? DateOfBirth { get; set; }

        [Required(ErrorMessage = "Please Enter The Contact Number")]
        [Phone]
        public string ContactNumber { get; set; }

        [Required(ErrorMessage = "Please Enter The City")]
        public string City { get; set; }

        [Required(ErrorMessage = "Please Enter The State")]
        public string State { get; set; }

        [Required(ErrorMessage = "Please Enter The Name")]
        public string Zipcode { get; set; }

        [Required(ErrorMessage = "Please Enter The Password")]
        public string Password { get; set; }


        public virtual ICollection<Booking> Bookings { get; set; }
        public virtual ICollection<Contactus> Contactus { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual ICollection<Signin> Signins { get; set; }
    }
}
